name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.6.*" 
          enable-cache: true

      - name: Install PostgreSQL and PostGIS
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib postgresql-16-postgis-3
          sudo service postgresql start
          pg_isready

      - name: Install dependencies
        run: |
          uv sync 

      # - name: run pre-commit
      #   if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
      #   run: |
      #     uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest

  publish:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase REPO for docker image name
        id: downcase
        run: |
          repo_name=${{ github.repository }}
          echo "repo=${repo_name,,}" >> $GITHUB_OUTPUT

      - name: Build and push stactools-ingest-load image
        run: |
          docker build -t ghcr.io/${{ steps.downcase.outputs.repo }}/stactools-ingest-load -f ./infrastructure/item_load/Dockerfile .
          docker push ghcr.io/${{ steps.downcase.outputs.repo }}/stactools-ingest-load

      - name: Build and push stactools-ingest-gen image
        run: |
          docker build -t ghcr.io/${{ steps.downcase.outputs.repo }}/stactools-ingest-gen -f ./infrastructure/item_gen/Dockerfile .
          docker push ghcr.io/${{ steps.downcase.outputs.repo }}/stactools-ingest-gen

